Loyal
22Fariz22/loyal pull request #1
Opened 2023-03-01 11:18 UTC by 22Fariz22

2023-03-02 20:55 UTC, Bazys requested changes

2023-03-02 20:55 UTC, Bazys commented on cmd/gophermart/main.go
> +	log.Println("len(os.Args) ", len(os.Args))
при PR в мастер, такое убирают

2023-03-02 20:55 UTC, Bazys commented on internal/app/app.go
> +	//log.Println("viper.GetString('a'): ", viper.GetString("a"))
тоже самое

2023-03-02 20:55 UTC, Bazys commented on internal/app/app.go
> +	userRepo := postgres2.NewUserRepository(db)
ну ты сам понимаешь что у тебя что то не то с именованием модулей

2023-03-02 21:26 UTC, 22Fariz22 commented on internal/app/app.go
> +	userRepo := postgres2.NewUserRepository(db)
IDE сам предложил так называть. а как их еще назвать? папки то у них одинаковые. например orderpostgres?

2023-03-04 10:50 UTC, Bazys approved these changes

2023-03-04 12:09 UTC, merged